#!/bin/bash

mkdir -p out/Release
cd out/Release

export PATH=$PATH:E:/github/lib2/dawn/third_party/llvm-build/Release+Asserts/bin


cmake \
-GNinja \
-DCMAKE_BUILD_TYPE=Release \
-DTINT_ENABLE_INSTALL=ON \
-DTINT_BUILD_TESTS=OFF \
-DDAWN_BUILD_TESTS=OFF \
-DDAWN_BUILD_SAMPLES=OFF \
-DDAWN_BUILD_MONOLITHIC_LIBRARY=STATIC \
-DTINT_BUILD_SPV_READER=ON \
-DTINT_BUILD_WGSL_READER=ON \
-DTINT_BUILD_GLSL_WRITER=ON \
-DTINT_BUILD_GLSL_VALIDATOR=ON \
-DTINT_BUILD_HLSL_WRITER=ON \
-DTINT_BUILD_MSL_WRITER=ON \
-DTINT_BUILD_SPV_WRITER=ON \
-DTINT_BUILD_WGSL_WRITER=ON \
-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded \
-DABSL_MSVC_STATIC_RUNTIME=ON \
../..

ninja